# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nodey < Formula
  desc "AI-Powered Flowchart Architect for your Terminal"
  homepage "https://github.com/DN-OpenSource/nodey"
  version "1.0.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DN-OpenSource/nodey/releases/download/v1.0.6/nodey_darwin_amd64.tar.gz"
      sha256 "dcb08680339d5543ceda9a9d15a2ab4537e266ea991e7807cec0fb7a5cdf43ba"

      def install
        bin.install "nodey"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DN-OpenSource/nodey/releases/download/v1.0.6/nodey_darwin_arm64.tar.gz"
      sha256 "53bd96f7b1c391e023cdc20ef338842c2703c900092444634d19532ff39f3b85"

      def install
        bin.install "nodey"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/DN-OpenSource/nodey/releases/download/v1.0.6/nodey_linux_amd64.tar.gz"
      sha256 "d6accfd9f92f43bfa7d49c09d59fd7eb439401b7eb5770c7d0bbc8238ff1cdda"
      def install
        bin.install "nodey"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DN-OpenSource/nodey/releases/download/v1.0.6/nodey_linux_arm64.tar.gz"
      sha256 "8fa531192257c45d3ffca41940609108b62f84e799a256a1d28faec8ca9c0cd7"
      def install
        bin.install "nodey"
      end
    end
  end
end
