# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nodey < Formula
  desc "AI-Powered Flowchart Architect for your Terminal"
  homepage "https://github.com/dhirajnikam/nodey"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dhirajnikam/nodey/releases/download/v1.0.0/nodey_darwin_amd64.tar.gz"
      sha256 "8f041fcc097f29322be35d5b394cbe049a424c5d2bb5f294c46a4ca4d0878727"

      def install
        bin.install "nodey"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dhirajnikam/nodey/releases/download/v1.0.0/nodey_darwin_arm64.tar.gz"
      sha256 "84b72e16e6fdab894d2230e43783e9ea5b675e2dfbe228a1a5cc98859d2e66c7"

      def install
        bin.install "nodey"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dhirajnikam/nodey/releases/download/v1.0.0/nodey_linux_amd64.tar.gz"
      sha256 "ee0342356e069dcd1a058b13979cd6ad7e934a04653f414ebaa6e9a42529130e"
      def install
        bin.install "nodey"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dhirajnikam/nodey/releases/download/v1.0.0/nodey_linux_arm64.tar.gz"
      sha256 "f3a961bc65d5344e9b4d0f5aefd42400efcdb2baaec51dc8bd2ae707ec666e0f"
      def install
        bin.install "nodey"
      end
    end
  end
end
